### ISSUE TITLE
CSS property not applied: `font-variant-numeric: oldstyle-nums`

### ISSUE THREAD

**Issue by efermi** [buggins/coolreader#294]
The property is being used in the core CSS of standardebooks.org epubs, see for example https://standardebooks.org/ebooks/p-g-wodehouse/jeeves-stories, and it is not applied to the rendered text even if the font supports oldstyle-nums. I'm not familiar with the project and therefore the following assumption may be wrong, but a search [reveals](https://github.com/buggins/coolreader/search?q=LFNT_OT_FEATURES_P_ONUM) that the feature should be supported given that `font-variant: small-caps` found nearby is being properly rendered.
Here pictured in comparison cr3 (left) and ebook-viewer of calibre which renders `oldstyle-nums` as intended:
![Screenshot_20210525_000640](https://user-images.githubusercontent.com/3966555/119407612-217c5700-bced-11eb-8591-a003de4f4ff2.png)
_1915_ and _1925_ -- oldstyle numerals, _P. G. Wodehouse_ and _Standard Ebooks project_ -- small capitals.

**Comment by poire-z** [comment]
It is supported (there might be a few caveats with inheritance, but they shouldn't trigger in the case of this book) https://github.com/koreader/koreader/issues/5821#issuecomment-600225376

The issue with this book is that our CSS parser is confused by some stuff at the start of epub/css/core.css, which makes it skip the first declaration (bug https://github.com/koreader/koreader/issues/7199):
```css
@charset "utf-8";
@namespace epub "http://www.idpf.org/2007/ops";  /* this is what we don't handle well */

dummy {}  /* add a first dummy declaration and the next one works */
body{
        font-variant-numeric: oldstyle-nums;
        hyphens: auto;
            color: blue; /* just to be sure it applies */
        -epub-hyphens: auto;
}

```
